Add ContextSnapshot.captureFromMany variants
micrometer-metrics/context-propagation pull request #98
Opened 2023-05-09 13:58 UTC by bclozel

Prior to this commit, `ContextSnapshot` would only allow to capture from
a single context, unless the `captureAll` variants which involve
`ThreadLocal` capture.

This commit introduces new `captureFromMany` methods for this, since
introducing varargs variants for `captureFrom` would break existing
applications.
This new method allows to capture a context snapshot from multiple
contexts (without capturing from threadlocals). If a particular
key is present in multiple contexts, it will be overriden as values are
extracted.

2023-05-09 14:00 UTC, bclozel commented
This PR is in draft mode currently - there is a use case for this in Spring for GraphQL instrumentation.

2023-05-10 08:44 UTC, rstoyanchev commented
To clarify the scenario, the GraphQL Java `DataFetchingEnvironment` has a "main", per-request `GraphQLContext` object in addition to any number of local ones for specific fields (and sub-fields below them). Until now only the main context was used, but there is a need to overlay that with local context.

2023-05-10 08:55 UTC, rstoyanchev requested changes
Overall a straight forward change. In retrospect, the `captureFrom` methods should have been vaarg methods from the start, just like `captureAll`. Be it as it may, we can either double the number of `captureFrom~` methods for a total of 6, or we can correct via deprecations. My thought is to rename the proposed `captureFromMany` to `captureFromContext`, and deprecate `captureFrom` eventually to be removed.

What do you think @chemicL, @marcingrzejszczak ?

2023-05-11 07:23 UTC, chemicL commented
Looks good to me, thanks for aligning the method names, too.

2023-05-11 07:24 UTC, chemicL approved these changes

2023-05-11 11:20 UTC, closed without merging